version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    target-branch: dev
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: '@types/node'
      - dependency-name: '@typescript-eslint/*'
        update-types:
          - 'version-update:semver-major'
    groups:
      typescript:
        patterns:
          - '@typescript-eslint/*'
          - typescript
        update-types:
          - minor
          - patch