version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    target-branch: dev
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: '@types/node'
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'