'on':
  pull_request: ~
  push:
    branches:
      - dev
  workflow_dispatch: ~
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.16.0
      - shell: bash
        run: |
          npm ci
          npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.16.0
      - shell: bash
        run: |
          npm ci --omit dev
          cp config/default-example.yaml config/default.yaml
          npm run build
